### ISSUE TITLE
Missing Force Bridge tokens on mainnet and testnet bridge

### ISSUE THREAD

**Issue by Kuzirashi** [zhangyouxin/light-godwoken#115]
Expected: Bridge allows to withdraw from Godwoken v0 all tokens that are available in Force Bridge (both on testnet and mainnet).

Actual: Only ETH (from Force Bridge), TAI and USDC (not from Force Bridge) are possible to withdraw.

Screenshot from mainnet deployment:

![image](https://user-images.githubusercontent.com/4950658/173590607-ea665cd1-1768-4633-9557-2782628d0064.png)

**Comment by zhangyouxin** [comment]
Closed by https://github.com/zhangyouxin/light-godwoken/pull/118
